# Generated by Django 5.1 on 2024-08-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='speaker',
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
    ]
